name: CI Build
on:
  push:
    branches:
      - release

jobs:
  check-folders:
    runs-on: ubuntu-latest
    outputs:
      run_build_job: ${{ steps.check.outputs.run_build_job }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: check if files have been updated
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == src/main/* ]]; then
              echo "This modified file is in the 'src/main/' folder."
              echo "run_build_job=true" >> $GITHUB_OUTPUT
            elif [[ $file == src/test/* ]]; then
              echo "This modified file is in the 'src/test/' folder."
              echo "run_build_job=true" >> $GITHUB_OUTPUT
            else
              echo "This modified file not associated with any of the packages."
            fi
          done < files.txt
        id: check

  build:
    runs-on: ubuntu-latest
    needs:
      - check-folders
    if: ${{ needs.check-folders.outputs.run_build_job == 'true' }}
    steps:
      -   name: Check out the repo
          uses: actions/checkout@v3

      -   name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'

      -   name: Build with Maven
          run: mvn package

      -   name: Run docker compose
          run: docker-compose up --abort-on-container-exit